In [1]:
import numpy as np

We compute the matrix multiplication

$$
\begin{bmatrix}
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}
\begin{bmatrix}
1 \\
2 \\
3
\end{bmatrix}.
$$

The dimensions are $(2 \times 3)(3 \times 1)$, so the result is a $(2 \times 1)$ vector.

First row:
$$
0\cdot 1 + 1\cdot 2 + 0\cdot 3 = 2.
$$

Second row:
$$
0\cdot 1 + 0\cdot 2 + 1\cdot 3 = 3.
$$

Therefore,

$$
\begin{bmatrix}
2 \\
3
\end{bmatrix}.
$$

In [2]:
X = np.array([[0, 1, 0], [0, 0, 1]])
X, X.shape

(array([[0, 1, 0],
        [0, 0, 1]]),
 (2, 3))

In [3]:
w = np.array([1,2,3])[:, None]

In [4]:
X @ w, (X @ w).shape

(array([[2],
        [3]]),
 (2, 1))

In [5]:
X + 10 

array([[10, 11, 10],
       [10, 10, 11]])

In [6]:
X + 10 * np.ones_like(X)

array([[10, 11, 10],
       [10, 10, 11]])

In [7]:
A = np.array([[1,2,3],[4,5,6]])
b = np.array([10, 20, 30])
A, b

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([10, 20, 30]))

In [8]:
A.shape, b.shape

((2, 3), (3,))

In [9]:
b[None, :].shape

(1, 3)

In [10]:
b[None, :] + A

array([[11, 22, 33],
       [14, 25, 36]])